# Theme Settings
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air" # Options: air, aqua, contrast, midnight

# Site Information
title: "Ali Eastman Oku MSc"
name: "Ali Oku"
description: "Bioinformatician | Data Scientist"
url: "https://eastmanmd.github.io"
baseurl: "" # Leave empty if your repo is eastmanmd.github.io

# Navigation
navigation:
  - title: "Resume"
    url: /resume/
  - title: "Code Reviews"
    url: /code-reviews/
  - title: "Paper Reviews"
    url: /paper-reviews/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-include-cache

# Defaults for Layouts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      share: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
